name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install system libraries required for R packages
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev pandoc pandoc-citeproc

      # Step 4: Install a minimal LaTeX distribution
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      # Step 5: Set CRAN repository to avoid mirror issues
      - name: Set CRAN repository
        run: echo "options(repos = c(CRAN = 'https://cloud.r-project.org'))" > ~/.Rprofile

      # Step 6: Install the 'gt' package explicitly
      - name: Install gt package
        run: Rscript -e 'install.packages("gt", repos = "https://cloud.r-project.org")'

      # Step 7: Install all other dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # Step 8: Build and check the R package
      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check --as-cran *.tar.gz
